kind: Service
apiVersion: v1
metadata:
  name: parrot-network-service
spec:
  type: NodePort
  selector:
    app: parrot-network
  ports:
  - protocol: TCP
    port: 9080
    nodePort: 9080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parrot-network-deployment
  labels:
    app: parrot-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parrot-network
      track: stable
  template:
    metadata:
      labels:
        app: parrot-network
        track: stable
    spec:
      containers:
      - name: parrot-network
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 9080
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m